use_frameworks!

platform :ios, '11.0'

target 'LithoModels_Example' do
  pod 'LithoModels', :path => '../'

  target 'LithoModels_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
